# Generated by Django 2.2 on 2020-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(max_length=12, verbose_name='TC Kimliği')),
                ('firstName', models.CharField(max_length=55, verbose_name='Ad')),
                ('lastName', models.CharField(max_length=55, verbose_name='Soyad')),
                ('length', models.CharField(max_length=3, verbose_name='Boy')),
                ('age', models.CharField(max_length=3, verbose_name='Yaş')),
                ('sex', models.CharField(max_length=20, verbose_name='Cinsiyet')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
                ('country', models.CharField(max_length=12, verbose_name='Ülke')),
                ('uniformity_cell_shape', models.IntegerField()),
                ('marginal_adhesion', models.IntegerField()),
                ('single_epithelial_cell_size', models.IntegerField()),
                ('bare_nuclei', models.IntegerField()),
                ('bland_chromatin', models.IntegerField()),
                ('normal_nucleoli', models.IntegerField()),
                ('mitoses', models.IntegerField()),
                ('result', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
