# Generated by Django 2.2 on 2020-05-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0002_cancer_h'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancer',
            old_name='h',
            new_name='uniformity_cell_size',
        ),
    ]
