# Generated by Django 2.2 on 2020-05-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0003_auto_20200507_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancer',
            name='description',
        ),
    ]
