# Generated by Django 2.2 on 2020-06-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0005_contactformmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormMessage',
        ),
    ]
